spring.application.name=expenseTracker

# Database Connection (Reads the full URL from your Render environment variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

# Looks for OAUTH_CLIENT_SECRET in the environment. If not found, defaults to 'my-local-secret'
oauth2.client.secret=${OAUTH_CLIENT_SECRET:my-local-secret}

server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always